import "./globals.css";
import "swiper/swiper.css";
import "../node_modules/react-modal-video/css/modal-video.css";
import "@/styles/css/base.css";
import "@/styles/css/custom.css";
import "@/styles/css/fontawesome-all.min.css";
import "@/styles/css/fontello.css";
import "@/styles/css/justified.css";
import "@/styles/css/magnific-popup.css";
import "@/styles/css/nice-select.css";
import "@/styles/css/style.css";

import type { Metadata } from "next";
import { Open_Sans, Rubik } from "next/font/google";
import CookiesBanner from "@/components/CookiesBanner";
import DesktopHeader from "@/components/layout/desktop-header";
import Footer from "@/components/layout/footer";
import MobileHeader from "@/components/layout/mobile-header";

const rubik = Rubik({
  subsets: ["latin"],
  display: "swap",
  variable: "--Rubik",
});
const openSans = Open_Sans({
  subsets: ["latin"],
  display: "swap",
  variable: "--OpenSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${rubik.variable} ${openSans.variable}`}
    >
      <body>
        <div className="industify_fn_wrapper_all">
          <div className="industify_fn_wrapper">
            <DesktopHeader />
            <MobileHeader />
            {children}
            <Footer />
            <CookiesBanner />
          </div>
        </div>
      </body>
    </html>
  );
}
